### ISSUE TITLE
NetInfo has been extracted from react-native

### ISSUE THREAD

**Issue by jsina** [rgommezz/react-native-offline#197] opened 2019-07-05 08:32 UTC
because the NetInfo is gonna extracted and gonna be removed from react-native core I've got this warning: 

> Warning: NetInfo has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/netinfo' instead of 'react-native'.
is there any update for new version?

**Comment by adam-s** [comment] 2019-07-11 00:23
````
/* @flow */
/* eslint flowtype/require-parameter-type: 0 */
import { put, select, call, take, cancelled, fork } from 'redux-saga/effects';
import { eventChannel } from 'redux-saga';
import { AppState, NetInfo, Platform } from 'react-native';
import { networkSelector } from './reducer';
import checkInternetAccess from '../utils/checkInternetAccess';
import { connectionChange } from './actionCreators';
import type { HTTPMethod } from '../types';
import {
  DEFAULT_HTTP_METHOD,
  DEFAULT_PING_SERVER_URL,
  DEFAULT_TIMEOUT,
} from '../utils/constants';

type Arguments = {
  pingTimeout: number,
  pingServerUrl: string,
  shouldPing: boolean,
  pingInterval: number,
  pingOnlyIfOffline: boolean,
  pingInBackground: boolean,
  httpMethod: HTTPMethod,
};
````
Should become
````
/* @flow */
/* eslint flowtype/require-parameter-type: 0 */
import { put, select, call, take, cancelled, fork } from 'redux-saga/effects';
import { eventChannel } from 'redux-saga';
import NetInfo from '@react-native-community/netinfo';
import { AppState, Platform } from 'react-native';
import { networkSelector } from './reducer';
import checkInternetAccess from '../utils/checkInternetAccess';
import { connectionChange } from './actionCreators';
import type { HTTPMethod } from '../types';
import {
  DEFAULT_HTTP_METHOD,
  DEFAULT_PING_SERVER_URL,
  DEFAULT_TIMEOUT,
} from '../utils/constants';

type Arguments = {
  pingTimeout: number,
  pingServerUrl: string,
  shouldPing: boolean,
  pingInterval: number,
  pingOnlyIfOffline: boolean,
  pingInBackground: boolean,
  httpMethod: HTTPMethod,
};
````

**Comment by kneza23** [comment] 2019-07-16 09:17
Yeah this is a issue on the >= 0.60 versions. Any plans to create a PR and merge?

**Comment by adam-s** [comment] 2019-07-16 15:10
I don't know how to make it backwards compatible so I didn't create a PR. I wasn't sure how to import a file based on react-native version. 

I created a new file in the `sagas` directory at `./src/sagas/offlineNetwork.js` with the update.
````
import {
  put,
  select,
  call,
  take,
  cancelled,
  fork,
} from 'redux-saga/effects';
import { eventChannel } from 'redux-saga';
import { AppState, Platform } from 'react-native';
import NetInfo from '@react-native-community/netinfo';
import { networkSelector } from 'react-native-offline/src/redux/reducer';
import checkInternetAccess from 'react-native-offline/src/utils/checkInternetAccess';
import { connectionChange } from 'react-native-offline/src/redux/actionCreators';
import {
  DEFAULT_HTTP_METHOD,
  DEFAULT_PING_SERVER_URL,
  DEFAULT_TIMEOUT,
} from 'react-native-offline/src/utils/constants';

export function netInfoEventChannelFn(emit) {
  NetInfo.addEventListener(emit);
  return () => {
    NetInfo.removeEventListener(emit);
  };
}

export function intervalChannelFn(interval) {
  return (emit) => {
    const iv = setInterval(() => emit(true), interval);
    return () => {
      clearInterval(iv);
    };
  };
}

/**
 * Returns a factory function that creates a channel from network connection change events
 * @returns {Channel<T>}
 */
export function createNetInfoConnectionChangeChannel(channelFn) {
  return eventChannel(channelFn);
}

/**
 * Returns a factory function that creates a channel from an interval
 * @param interval
 * @param channelFn
 * @returns {Channel<T>}
 */
export function createIntervalChannel(interval, channelFn) {
  const handler = channelFn(interval);
  return eventChannel(handler);
}

/**
 * Creates a NetInfo change event channel that:
 * - Listens to NetInfo connection change events
 * - If shouldPing === true, it first verifies we have internet access
 * - Otherwise it calls handleConnectivityChange immediately to process the new information into the redux store
 * @param pingTimeout
 * @param pingServerUrl
 * @param shouldPing
 * @param httpMethod
 */
export function* netInfoChangeSaga({
  pingTimeout,
  pingServerUrl,
  shouldPing,
  httpMethod,
}) {
  if (Platform.OS === 'android') {
    const initialConnection = yield call([NetInfo, NetInfo.fetch]);
    yield fork(connectionHandler, {
      shouldPing,
      isConnected: initialConnection,
      pingTimeout,
      pingServerUrl,
      httpMethod,
    });
  }
  const chan = yield call(
    createNetInfoConnectionChangeChannel,
    netInfoEventChannelFn,
  );
  try {
    while (true) {
      const isConnected = yield take(chan);
      yield fork(connectionHandler, {
        shouldPing,
        isConnected,
        pingTimeout,
        pingServerUrl,
        httpMethod,
      });
    }
  } finally {
    if (yield cancelled()) {
      chan.close();
    }
  }
}

/**
 * Either checks internet by pinging a server or calls the store handler function
 * @param shouldPing
 * @param isConnected
 * @param pingTimeout
 * @param pingServerUrl
 * @param httpMethod
 * @returns {IterableIterator<ForkEffect | *>}
 */
export function* connectionHandler({
  shouldPing,
  isConnected,
  pingTimeout,
  pingServerUrl,
  httpMethod,
}) {
  if (shouldPing && isConnected) {
    yield fork(checkInternetAccessSaga, {
      pingTimeout,
      pingServerUrl,
      httpMethod,
    });
  } else {
    yield fork(handleConnectivityChange, isConnected);
  }
}

/**
 * Creates an interval channel that periodically verifies internet access
 * @param pingTimeout
 * @param pingServerUrl
 * @param interval
 * @param pingOnlyIfOffline
 * @param pingInBackground
 * @param httpMethod
 * @returns {IterableIterator<*>}
 */
export function* connectionIntervalSaga({
  pingTimeout,
  pingServerUrl,
  pingInterval,
  pingOnlyIfOffline,
  pingInBackground,
  httpMethod,
}) {
  const chan = yield call(
    createIntervalChannel,
    pingInterval,
    intervalChannelFn,
  );
  try {
    while (true) {
      yield take(chan);
      const { isConnected } = yield select(networkSelector);
      if (!(isConnected && pingOnlyIfOffline === true)) {
        yield fork(checkInternetAccessSaga, {
          pingTimeout,
          pingServerUrl,
          httpMethod,
          pingInBackground,
        });
      }
    }
  } finally {
    if (yield cancelled()) {
      chan.close();
    }
  }
}

/**
 * Saga that verifies internet connection, besides connectivity, by pinging a server of your choice
 * @param pingServerUrl
 * @param pingTimeout
 * @param httpMethod
 * @param pingInBackground
 */
export function* checkInternetAccessSaga({
  pingServerUrl,
  pingTimeout,
  httpMethod,
  pingInBackground,
}) {
  if (pingInBackground === false && AppState.currentState !== 'active') {
    return; // <-- Return early as we don't care about connectivity if app is not in foreground.
  }
  const hasInternetAccess = yield call(checkInternetAccess, {
    url: pingServerUrl,
    timeout: pingTimeout,
    method: httpMethod,
  });
  yield call(handleConnectivityChange, hasInternetAccess);
}

/**
 * Takes action under the new network connection value:
 * - Dispatches a '@@network-connectivity/CONNECTION_CHANGE' action type
 * - Flushes the queue of pending actions if we are connected back to the internet
 * @param hasInternetAccess
 */
export function* handleConnectivityChange(
  hasInternetAccess,
) {
  const { isConnected } = yield select(networkSelector);
  if (isConnected !== hasInternetAccess) {
    yield put(connectionChange(hasInternetAccess));
  }
}

/**
 * Saga that controls internet connectivity in your whole application.
 * You just need to fork it from your root saga.
 * It receives the same parameters as withNetworkConnectivity HOC
 * @param pingTimeout
 * @param pingServerUrl
 * @param shouldPing
 * @param pingInterval
 * @param pingOnlyIfOffline
 * @param pingInBackground
 * @param httpMethod
 */
export default function* networkSaga({
  pingTimeout = DEFAULT_TIMEOUT,
  pingServerUrl = DEFAULT_PING_SERVER_URL,
  shouldPing = true,
  pingInterval = 0,
  pingOnlyIfOffline = false,
  pingInBackground = false,
  httpMethod = DEFAULT_HTTP_METHOD,
}) {
  yield fork(netInfoChangeSaga, {
    pingTimeout,
    pingServerUrl,
    shouldPing,
    pingOnlyIfOffline,
    pingInBackground,
    httpMethod,
  });
  if (pingInterval > 0) {
    yield fork(connectionIntervalSaga, {
      pingTimeout,
      pingServerUrl,
      pingInterval,
      pingOnlyIfOffline,
      pingInBackground,
      httpMethod,
    });
  }
}
````

then I imported it into the `network.js` file

````
import {
  call,
  put,
  fork,
  select,
  takeLatest,
  delay,
} from 'redux-saga/effects';
import NetInfo from '@react-native-community/netinfo';
import { offlineActionTypes } from 'react-native-offline';

import networkSaga from './offlineNetwork';
import { ping } from '../services/network';
````

**Comment by rgommezz** [comment] 2019-07-18 11:30
Duplicate of #172

**Closed by rgommezz** 2019-07-18 11:30 UTC

**Comment by anupgusain** [comment] 2020-01-09 09:23
Hi friends quick fix for Net Info error with redux offline
use redux-offline version @redux-offline/redux-offline: "2.5.2-native.0"

and if you get error handler is not a function, handler is "change" then use
@react-native-community/netinfo: "4.7.0"

read #339 (comment) of @sorodrigo

**Comment by rcbevans** [comment] 2020-01-24 03:29
I get a new error after switching redux-offline version:

![image](https://user-images.githubusercontent.com/2041260/73042623-b5e35a80-3e16-11ea-8a6a-a88db9ae45d4.png)

**Comment by kneza23** [comment] 2020-01-24 08:56
> I get a new error after switching redux-offline version:
> 
> ![image](https://user-images.githubusercontent.com/2041260/73042623-b5e35a80-3e16-11ea-8a6a-a88db9ae45d4.png)

Same with me. Set version of netinfo to 5.1.0 and then it will work. It is a problem with react-native-offline.
