### ISSUE TITLE
Null values  in actionView array

### ISSUE THREAD

**Issue by ignivarahulsaini** [rgommezz/react-native-offline#40] opened 2017-09-19 13:37 UTC
Code:

export const getQuizs = (data) => {
  let obj={
    userId  : data.userId,
  }; 
  let thunk = (dispatch)=>{
    dispatch(loading_start({ type: LOADING_START }));
    RestClient.get('quizzes/getMyQuiz',obj).then((response) => {
      dispatch(loading_stop({ type: LOADING_STOP }));
    }).catch(error => {
      dispatch(loading_stop({ type: LOADING_STOP }));
    });
  }
  thunk.interceptInOffline = true; // This is the important part
  thunk.meta = {
    retry: true, // By passing true, your thunk will be enqueued on offline mode
    dismiss: ['NAVIGATE_BACK']
  }
  return thunk; // Return it afterwards

      After hitting this action in offline mode Null values  are coming in actionView array

**Comment by rauliyohmc** [comment] 2017-09-19 16:49
Could you please format your code?

**Comment by ignivarahulsaini** [comment] 2017-09-20 05:48
Code:
```javascript
export const getQuizs = (data) => {
      let thunk = (dispatch)=>{
     dispatch(loading_stop({ type: LOADING_START }));
     RestClient.get('quizzes/getMyQuiz',{id:1}).then((response) => {
          dispatch(loading_stop({ type: LOADING_STOP }));
    }).catch(error => {
     });
     }
    thunk.interceptInOffline = true; // This is the important part
    thunk.meta = {
        retry: true,
       dismiss: ['NAVIGATE_BACK']
    }
    return thunk; // Return it afterwards
} 
After hitting this action in offline mode Null values  are coming in actionView array

**Comment by rauliyohmc** [comment] 2017-09-21 22:40
So the internal action fired does present an empty `payload`? I see in your snippet `payload` is an empty object, but the internal action creator should generate a action with the next shape:

```js
{
  type: '@@network-connectivity/FETCH_OFFLINE_MODE',
  payload: {
    prevThunk: thunk
  },
  meta: {
    retry: true,
    dismiss: [
      'NAVIGATE_BACK',
      ''
    ]
  }
}
```

Could you tell me which `payload` you get when the action `@@network-connectivity/FETCH_OFFLINE_MODE` gets dispatched?

**Comment by ignivarahulsaini** [comment] 2017-09-25 07:52
Hi below is the @@network-connectivity/FETCH_OFFLINE_MODE's contents when it dispathed:

@@network-connectivity/FETCH_OFFLINaE_MODE : {"type":"@@network-connectivity/FETCH_OFFLINE_MODE","payload":{},"meta":{"retry":true}}

**Comment by rauliyohmc** [comment] 2017-10-03 22:54
I can't spot the issue based on your code. If you had a repository with the full code that would be great. Then I could take a better look.

**Comment by patilrevansidh** [comment] 2017-11-24 10:49
facing same problem as mentioned above :
action -
```
export const INCREMENTING = 'INCREMENTING';
export const DECREMENTING = 'DECREMENTING';
export const INCR_SUCCESS = 'INCR_SUCCESS'; 
export const INCR_FAIL = 'INCR_FAIL';  
export const DECR_SUCCESS = 'DECR_SUCCESS';
export const DECR_FAIL = 'DECR_FAIL';
import operationService from './service'

export const incrementAction = () => {
    async function thunk(dispatch) {
      try {
          dispatch({type:INCREMENTING},{meta:{retry:true}});
          const result =await operationService.doOperation({'type':'increment'})
          const value = JSON.parse(result._bodyInit).value
          dispatch({type:INCR_SUCCESS,payload:{number:value}});
      } catch (error) {
          dispatch({type:INCR_FAIL})
      }
    };
  
    thunk.interceptInOffline = true; // This is the important part
    return thunk; // Return it afterwards
};
```
reducer : 
```
const incrDcrReducer = (state, action) =>{
    switch(action.type) {              
        case "persist/REHYDRATE" : 
            return {...action.payload.redu}
        case INCREMENTING :
            return {...state}
        case INCR_SUCCESS :
            return {...state,number : action.payload.number};
        case INCR_FAIL :
            return {...state}
        case DECREMENTING :
            return {...state}
        case DECR_SUCCESS :
            return {...state,number : action.payload.number};
        case DECR_FAIL : 
            return {...state}
        default :
            return {...state}
    }
}

yes with redux-perist
![offlinelogger](https://user-images.githubusercontent.com/11453641/33207297-28547a84-d133-11e7-8bbd-bce06e285251.png)

**Comment by rgommezz** [comment] 2018-04-25 14:35
Duplicate of #35, let's follow up on that one

**Closed by rgommezz** 2018-04-25 14:35 UTC
Labels: needs more info
